# Site settings
title: Zink in Apps!
email: jmoreno@zinkinapps.com
url: https://zinkinapps.github.io
description: "Este es el sitio donde Zink in Apps! muestra al mundo su pequeña obra. No seas duro, ten en cuenta que todo esto se ha realizado en ratos libres de una única persona."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F67C05 #80B3FF
  secondary: 333 #FD6E8A
  secondary-dark: 212121 #A2122F

# Footer settings
footer:
  copyright: Zink in Apps!
  location: Localización
  social: En la web
  credits: Créditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zinkinapps
  - title: github
    url: http://github.com/zinkinapps

# Postal address (add as many lines as necessary)
address:
 - line: Madrid.

# Credits content
credits: 'Pensando, diseñando y programando.'

# Build settings
markdown: kramdown
permalink: pretty

# Collection settings
collections:
  zings:
    output: true
    permalink: /zings/:path/
